language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install codecov

script:
 - pyflakes instabot tests examples
 - pycodestyle --ignore=E501 instabot tests
 - pycodestyle --ignore=E402,E501 examples
 - py.test --cov=instabot --cov-report=xml
 - codecov

branches:
  only:
    - master
cache: pip
